export default cdoBarangayData = [
  { label: "Agusan", value: "Agusan" },
  { label: "Baikingon", value: "Baikingon" },
  { label: "Bulua", value: "Bulua" },
  { label: "Balubal", value: "Balubal" },
  { label: "Balulang", value: "Balulang" },
  { label: "Barangay 10 (Pob.)", value: "Barangay 10 (Pob.)" },
  { label: "Barangay 11 (Pob.)", value: "Barangay 11 (Pob.)" },
  { label: "Barangay 12 (Pob.)", value: "Barangay 12 (Pob.)" },
  { label: "Barangay 13 (Pob.)", value: "Barangay 13 (Pob.)" },
  { label: "Barangay 14 (Pob.)", value: "Barangay 14 (Pob.)" },
  { label: "Barangay 15 (Pob.)", value: "Barangay 15 (Pob.)" },
  { label: "Barangay 16 (Pob.)", value: "Barangay 16 (Pob.)" },
  { label: "Barangay 17 (Pob.)", value: "Barangay 17 (Pob.)" },
  { label: "Barangay 18 (Pob.)", value: "Barangay 18 (Pob.)" },
  { label: "Barangay 19 (Pob.)", value: "Barangay 19 (Pob.)" },
  { label: "Barangay 2 (Pob.)", value: "Barangay 2 (Pob.)" },
  { label: "Barangay 21 (Pob.)", value: "Barangay 21 (Pob.)" },
  { label: "Barangay 22 (Pob.)", value: "Barangay 22 (Pob.)" },
  { label: "Barangay 23 (Pob.)", value: "Barangay 23 (Pob.)" },
  { label: "Barangay 24 (Pob.)", value: "Barangay 24 (Pob.)" },
  { label: "Barangay 26 (Pob.)", value: "Barangay 26 (Pob.)" },
  { label: "Barangay 27 (Pob.)", value: "Barangay 27 (Pob.)" },
  { label: "Barangay 28 (Pob.)", value: "Barangay 28 (Pob.)" },
  { label: "Barangay 3 (Pob.)", value: "Barangay 3 (Pob.)" },
  { label: "Barangay 30 (Pob.)", value: "Barangay 30 (Pob.)" },
  { label: "Barangay 32 (Pob.)", value: "Barangay 32 (Pob.)" },
  { label: "Barangay 33 (Pob.)", value: "Barangay 33 (Pob.)" },
  { label: "Barangay 34 (Pob.)", value: "Barangay 34 (Pob.)" },
  { label: "Barangay 38 (Pob.)", value: "Barangay 38 (Pob.)" },
  { label: "Barangay 39 (Pob.)", value: "Barangay 39 (Pob.)" },
  { label: "Barangay 4 (Pob.)", value: "Barangay 4 (Pob.)" },
  { label: "Barangay 40 (Pob.)", value: "Barangay 40 (Pob.)" },
  { label: "Barangay 5 (Pob.)", value: "Barangay 5 (Pob.)" },
  { label: "Barangay 6 (Pob.)", value: "Barangay 6 (Pob.)" },
  { label: "Barangay 8 (Pob.)", value: "Barangay 8 (Pob.)" },
  { label: "Barangay 9 (Pob.)", value: "Barangay 9 (Pob.)" },
  { label: "Bayabas", value: "Bayabas" },
  { label: "Bayanga", value: "Bayanga" },
  { label: "Bonbon", value: "Bonbon" },
  { label: "Bugo", value: "Bugo" },
  { label: "Camaman-an", value: "Camaman-an" },
  { label: "Canitoan", value: "Canitoan" },
  { label: "Carmen", value: "Carmen" },
  { label: "Consolacion", value: "Consolacion" },
  { label: "Cugman", value: "Cugman" },
  { label: "Dansolihon", value: "Dansolihon" },
  { label: "F. S. Catanico", value: "F. S. Catanico" },
  { label: "Gusa", value: "Gusa" },
  { label: "Indahag", value: "Indahag" },
  { label: "Iponan", value: "Iponan" },
  { label: "Kauswagan", value: "Kauswagan" },
  { label: "Lapasan", value: "Lapasan" },
  { label: "Lumbia", value: "Lumbia" },
  { label: "Macabalan", value: "Macabalan" },
  { label: "Macasandig", value: "Macasandig" },
  { label: "Mambuaya", value: "Mambuaya" },
  { label: "Nazareth", value: "Nazareth" },
  { label: "Pagalungan", value: "Pagalungan" },
  { label: "Pagatpat", value: "Pagatpat" },
  { label: "Patag", value: "Patag" },
  { label: "Pigsag-an", value: "Pigsag-an" },
  { label: "Puerto", value: "Puerto" },
  { label: "Puntod", value: "Puntod" },
  { label: "San Simon", value: "San Simon" },
  { label: "Tablon", value: "Tablon" },
  { label: "Taglimao", value: "Taglimao" },
  { label: "Tagpangi", value: "Tagpangi" },
  { label: "Tignapoloan", value: "Tignapoloan" },
  { label: "Tuburan", value: "Tuburan" },
  { label: "Tumpagon", value: "Tumpagon" },
  { label: "Barangay 1 (Pob.)", value: "Barangay 1 (Pob.)" },
  { label: "Barangay 7 (Pob.)", value: "Barangay 7 (Pob.)" },
  { label: "Barangay 20 (Pob.)", value: "Barangay 20 (Pob.)" },
  { label: "Barangay 25 (Pob.)", value: "Barangay 25 (Pob.)" },
  { label: "Barangay 29 (Pob.)", value: "Barangay 29 (Pob.)" },
  { label: "Barangay 31 (Pob.)", value: "Barangay 31 (Pob.)" },
  { label: "Barangay 35 (Pob.)", value: "Barangay 35 (Pob.)" },
  { label: "Barangay 36 (Pob.)", value: "Barangay 36 (Pob.)" },
  { label: "Barangay 37 (Pob.)", value: "Barangay 37 (Pob.)" },
];
